/**
 * Shared structural types for request-like objects used by lib/util helpers.
 *
 * This module is type-only: it has no runtime output, so the CommonJS
 * modules that require() its siblings are unaffected by its existence.
 *
 * @module types
 */

/**
 * Minimal shape of a WPRequest-like object whose supported HTTP methods can
 * be checked.
 */
export interface MethodSupportRequestLike {
	_supportedMethods: string[];
}

/**
 * Minimal shape of a WPRequest-like object with a chainable `.param()`
 * setter, as required by the methods parameter-setter generates.
 */
export interface ParamRequestLike {
	param( key: string, value: unknown ): ParamRequestLike;
}

/**
 * A node in the route tree built by lib/route-tree.ts: represents one level
 * of a resource's URL path hierarchy. Non-leaf nodes branch into `children`
 * keyed by the next path segment; leaf nodes carry the HTTP `methods` they
 * support.
 */
export interface RouteTreeNode {
	component: string;
	namedGroup: boolean;
	level: number;
	names: string[];
	validate: ( input: string ) => boolean;
	children?: Record<string, RouteTreeNode>;
	methods?: string[];
}

/**
 * The shape of lib/data/default-routes.json values, and of the synthetic
 * route objects lib/wp-register-route.js builds for `.registerRoute()`.
 * `endpoints` is only read for its GET args, so its non-GET method entries
 * only need their `methods` key to be present.
 */
export interface RouteDefinition {
	namespace: string;
	methods?: string[];
	endpoints?: Array<{
		methods: string[];
		args: Record<string, unknown>;
	}>;
}

/**
 * A single resource's tree of RouteTreeNodes, keyed by level key (dynamic
 * segments keyed by capture-group pattern or name, static segments keyed by
 * their path component string). The top-level object for a resource also
 * carries `_getArgs`: a dictionary of every GET query parameter supported
 * anywhere within the resource's tree, used to select parameter mixins.
 */
export type RouteTreeLevels = Record<string, RouteTreeNode> & {
	_getArgs?: Record<string, unknown>;
};

/**
 * The dictionary built by lib/route-tree.ts's `build`: API namespaces mapped
 * to their resources, each resource mapped to its RouteTreeLevels tree.
 */
export type RouteTree = Record<string, Record<string, RouteTreeLevels>>;

/**
 * One entry of a HandlerSpec's `_levels` dictionary: the subset of a
 * RouteTreeNode's data needed to validate a URL path part at request time.
 */
export interface LevelOption {
	component: string;
	validate: ( input: string ) => boolean;
	methods?: string[];
}

/**
 * A path-part setter function, as returned by lib/path-part-setter.ts's
 * `create` and stored on a HandlerSpec's `_setters` dictionary.
 */
type PathPartSetterModule = typeof import( './path-part-setter' );
export type PathPartSetterFn = ReturnType<PathPartSetterModule[ 'create' ]>;

/**
 * The handler spec built by lib/resource-handler-spec.ts's `create`: an
 * intermediate representation of one resource's endpoint request handler,
 * later consumed by lib/endpoint-request.ts to build the handler's
 * constructor.
 */
export interface HandlerSpec {
	_path: Record<string, string>;
	_levels: Record<number, LevelOption[]>;
	_setters: Record<string, PathPartSetterFn>;
	_getArgs?: Record<string, unknown>;
}

/**
 * The constructor built by lib/endpoint-request.ts's `create`: an
 * EndpointRequest class extending WPRequest with the URL path setters and
 * GET-argument mixins for one specific resource. The instance shape is left
 * as `unknown` here because WPRequest itself is still an untyped module;
 * consumers that need its API (e.g. to assign further prototype methods)
 * narrow locally, as lib/wp-register-route.js will in a later layer.
 */
export type EndpointRequestCtor = new ( options?: Record<string, unknown> ) => unknown;

/**
 * Minimal shape of the object an EndpointFactory may be called with as
 * `this`: carries the options (endpoint, auth, transport, etc.) to merge into
 * newly-created request handler instances.
 */
export interface EndpointFactoryContext {
	_options?: Record<string, unknown>;
}

/**
 * An endpoint request handler factory, as generated by
 * lib/endpoint-factories.ts's `generate`: a function that instantiates the
 * resource's EndpointRequest, carrying the constructor itself as `.Ctor` so
 * that generated handlers may be further customized when needed.
 */
export interface EndpointFactory {
	( this: EndpointFactoryContext, options?: Record<string, unknown> ): unknown;
	Ctor: EndpointRequestCtor;
}

/**
 * Minimal shape of a WPRequest-like object whose URL path parts can be set,
 * as required by the closures path-part-setter generates.
 */
export interface PathPartRequestLike extends MethodSupportRequestLike {
	setPathPart( level: number, val: string | number ): PathPartRequestLike;
}

/**
 * Minimal shape of a WPRequest-like object as consumed by the filter and
 * parameter mixins: adds the filter-storage properties those mixins read and
 * write, alongside the chainable `.param()` setter.
 */
export interface FilterRequestLike extends ParamRequestLike {
	_filters?: Record<string, unknown>;
	_taxonomyFilters?: Record<string, Array<string | number>>;
	param( key: string, value: unknown ): FilterRequestLike;
}
